---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 17425.
--- DateTime: 2021/12/19 23:04

require("BaseRequire")

function LuaStart()
    UIManager:Init()
    --print("logic start")
    --UpdateManager:GetInstance():Startup()
    --Game:OnInitOK()
end

--[[UpdateBeat 			= event("Update")
LateUpdateBeat		= event("LateUpdate")
FixedUpdateBeat		= event("FixedUpdate")]]

--[[
function Update1(deltaTime, unscaledDeltaTime)
end

function LateUpdate1()
  
end

function FixedUpdate1(fixedDeltaTime)
    
end]]
